# Generated by Django 2.1.4 on 2018-12-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_pessoal_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoal',
            options={'verbose_name_plural': 'Novas Pessoinhas'},
        ),
    ]
